# Generated by Django 2.0.6 on 2018-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
